# client
port : 2000
host : '127.0.01'

# general      
general:  
  save : False
  save_interval : 1 # save a scene copy every save_interval
  batch_size: 1 # size of the batch been written to disk
  show: True

# cameras
cameras:
  cam1:
    enable: True
    image_x : 800
    image_y : 600
    fov : 110
    location:
      x: 1.1
      y: 0
      z: 2
    orientation:
      pitch: 0
      yaw: 0
      roll: 0

  cam2:
    enable: False
    image_x : 800
    image_y : 600
    fov : 110
    location:
      x: -1.4
      y: 0
      z: 2
    orientation:
      pitch: 0
      yaw: 180
      roll: 0

camera_types: ['rgb','seg','dep']

actors:
  car: 'model3'

# logs
logs:
  root: 'logs'
  level: debug
  rotation_when: 'w0'
  rotation_backupcount: 0
